// unicode glyph:  - don't remove, needed for Windows bug
/**
 * Available Styles:
 * 0.  rfb_old
 * 1.  rfb
 * 2.  rfb_inland_border
 * 3.  rfb_inland_noborder
 * 4.  rfb_inland_unspecified_border 
 * 5.  rfb_inland_unspecified_noborder
 * 6.  rfb_marine_border
 * 7.  rfb_marine_inland_border
 * 8.  rfb_marine_inland_noborder
 * 9.  rfb_marine_noborder
 * 10. rfb_marine_regulatory_border
 * 11. rfb_marine_regulatory_noborder
 * 12. rfb_marine_unspecified_border
 * 13. rfb_marine_unspecified_noborder 
 * 14. rfb_unspecified_border 
 * 15. rfb_unspecified_noborder 
 * 16. rfb_marine_inland_unspecified_noborder
 * 17. rfb_marine_unspecified_inland_noborders
 **/

// FIXED ZOOM TO FOR SOME RFB TYPE (ZOOM TO WRAPDATELINE FEATURES)
var vmeViewerRFBZoomTo = {
    SPRFMO : {isWrapDateLine: true, zoomExtent: new OpenLayers.Bounds(-50, -60, 100, 10)},
    NPFC : {isWrapDateLine: true, zoomExtent: new OpenLayers.Bounds(-55, 15, 75, 55)},
	NEAFC : {isWrapDateLine: false, zoomExtent: new OpenLayers.Bounds(-78.93, 32.38, 82.77, 77.23)},
	NAFO : {isWrapDateLine: false, zoomExtent: new OpenLayers.Bounds(-121.75710936669134, 13.121674445496733, 25.899140612752504, 68.12634423147448)}
}


// Use the "skip" property (set to true) if the RFB shouldn't be listed in select
var rfbLayerSettings = {
/*
	APFIC		: { type: 'MI', style: 'rfb_inland_unspecified_noborder', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(90.0, 0.0), zoomExtent: new OpenLayers.Bounds(-13, 70, 170.0, -50) },
	'BOBP-IGO'	: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: false, globalZoom: false, centerCoords: null, zoomExtent: new OpenLayers.Bounds(31.0, -14.5, 125.0, 45.5) },
	CACFAC		: { type: 'I', style: 'rfb_inland_noborder', srs: '4326', isMasked: false,  globalZoom: false, centerCoords: new OpenLayers.LonLat(53.0, 43.0), zoomExtent: new OpenLayers.Bounds(9.0, 2.0, 97.0, 73.0) },
*/
	CCAMLR		: { type: 'M', style: 'rfb_marine_border', srs: '3031', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(0,0), zoomExtent: new OpenLayers.Bounds(-7666181, -5741041, 7666181, 5741041) },
/*
	CCBSP		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(20037508.34, 7800000.0), zoomExtent: new OpenLayers.Bounds(-5893240, 3922651, 5967525, 12804929.34) },
	CCSBT		: { type: 'M', style: 'rfb_marine_border', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(7000000, -2500000), zoomExtent: new OpenLayers.Bounds(-20037508.34, -20037508.34, 20037508.34, 20037508.34) },
	CECAF		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(2.0, 18.0), zoomExtent: new OpenLayers.Bounds(-100, -40, 83.0, 81)},
	CIFAA		: { type: 'I', style: 'rfb_inland_noborder', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(22.0, 0.0), zoomExtent: new OpenLayers.Bounds(-70, -50, 115.0, 60)},
	COMHAFAT	: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(2.0, 18.0), zoomExtent: new OpenLayers.Bounds(-100, -40, 83.0, 81)},
	COPESCAL	: { type: 'I', style: 'rfb_inland_noborder', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(-66, -11.0), zoomExtent: new OpenLayers.Bounds(-165, -65, 20.0, 50) },
	COREP		: { type: 'MI', style: 'rfb_marine_inland_noborder', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(16, 0.0), zoomExtent: new OpenLayers.Bounds(-30, -30, 60.0, 30)},
	CPPS		: { type: 'M', style: 'rfb_unspecified_noborder', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(-90, -23), zoomExtent: new OpenLayers.Bounds(-120, -60, -61.0, 15)},
	CRFM		: { type: 'MI', style: 'rfb_marine_unspecified_inland_noborders', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(-68, 18), zoomExtent: new OpenLayers.Bounds(-93.0, 0, -47, 33) },
	CTMFM		: { skip: true, type: 'M', style: 'rfb', srs: '4326', isMasked: true,  globalZoom: true,  centerCoords: null, zoomExtent: null },
	EIFAAC		: { type: 'I', style: 'rfb_inland_noborder', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(12, 48), zoomExtent: new OpenLayers.Bounds(-35, 20, 55, 80) },
	FCWC		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(0, 7), zoomExtent: new OpenLayers.Bounds(-45, -25, 45, 30) },
	FFA		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-19600000, -3200000), zoomExtent: new OpenLayers.Bounds(-12000000, -9000000, 5000000, 3000000) },
	GFCM		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(12, 48), zoomExtent: new OpenLayers.Bounds(-30, 15, 50, 75) },
	IATTC		: { type: 'M', style: 'rfb_marine_border', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-13400000, 1000000.0), zoomExtent: new OpenLayers.Bounds(-20037508.34, -20037508.34, 20037508.34, 20037508.34) },
	ICCAT		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-40, 0), zoomExtent: new OpenLayers.Bounds(-100, -85, 50, 90)},
	ICES		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(0, 60), zoomExtent: new OpenLayers.Bounds(-45, 32, 70, 90) },
	IOTC		: { type: 'M', style: 'rfb_marine_border', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(80, -10), zoomExtent: new OpenLayers.Bounds(-25, -56, 150, 75) },
	IPHC		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-17037508.34, 7800000.0), zoomExtent: new OpenLayers.Bounds(-5893240, 3922651, 5967525, 12804929.34) },
	IWC		: { type: 'M', style: 'rfb_unspecified_noborder', srs: '4326', isMasked: true,  globalZoom: true,  centerCoords: null, zoomExtent: null },
	LVFO		: { type: 'I', style: 'rfb_inland_noborder', srs: '4326', isMasked: false, globalZoom: false, centerCoords: new OpenLayers.LonLat(36.55, -2.6), zoomExtent: new OpenLayers.Bounds(0.778515625, -29.055078125, 72, 19.2) },
	MRC		: { type: 'I', style: 'rfb_inland_noborder', srs: '4326', isMasked: false, globalZoom: false, centerCoords: null, zoomExtent: new OpenLayers.Bounds(80.0, 1.0, 115.0, 32.0) },
*/
	NAFO		: { type: 'MR', style: 'rfb', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-60, 55), zoomExtent: new OpenLayers.Bounds(-85, 30, -35, 85) },
/*
	NAMMCO		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-20, 55), zoomExtent: new OpenLayers.Bounds(-85, 30, 70, 90) },
	NASCO		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-20, 55), zoomExtent: new OpenLayers.Bounds(-85, 30, 70, 90) },
// 	NEAFC		: { type: 'MR', style: 'rfb_marine_regulatory_border', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(0, 60), zoomExtent: new OpenLayers.Bounds(-45, 32, 70, 90) },
*/
	NEAFC		: { type: 'MR', style: 'rfb', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(5, 59), zoomExtent: new OpenLayers.Bounds(-43, 36, 51.5, 90) },
/*
	NPAFC		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(20037508.34, 7800000.0), zoomExtent: new OpenLayers.Bounds(-5893240, 3922651, 5967525, 12804929.34) },
	OLDEPESCA	: { type: 'MI', style: 'rfb_marine_unspecified_inland_noborders', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(-80, 10), zoomExtent: new OpenLayers.Bounds(-120, -30, -50, 35) },
	OSPESCA		: { type: 'MI', style: 'rfb_marine_unspecified_inland_noborders', srs: '4326', isMasked: false, globalZoom: false, centerCoords: null, zoomExtent: new OpenLayers.Bounds(-125.0, -16.0, -35.0, 45.0) },
	PICES		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-20037508.34, 7800000.0), zoomExtent: new OpenLayers.Bounds(-5693240, 3722651, 5767525, 10804929.34) },
	PSC		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-17037508.34, 7800000.0), zoomExtent: new OpenLayers.Bounds(-5893240, 3922651, 5967525, 12804929.34) },
	RECOFI		: { type: 'M', style: 'rfb_marine_border', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(51, 27), zoomExtent: new OpenLayers.Bounds(31, 7, 65, 45) },
	SEAFDEC		: { type: 'MI', style: 'rfb_marine_inland_unspecified_noborder', srs: '4326', isMasked: false, globalZoom: false,  centerCoords: new OpenLayers.LonLat(110, 10), zoomExtent: new OpenLayers.Bounds(70, -35, 155, 50)},
*/	SEAFO		: { type: 'M', style: 'rfb_marine_border', srs: '4326', isMasked: true,  globalZoom: false,  centerCoords: new OpenLayers.LonLat(-5, -30), zoomExtent: new OpenLayers.Bounds(-25, -55, 37, 10) }
/*	SIOFA		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(80, -10), zoomExtent: new OpenLayers.Bounds(-25, -56, 150, 75) },
	SPC		: { type: 'M', style: 'rfb_marine_border', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-19600000, -3200000), zoomExtent: new OpenLayers.Bounds(-12000000, -9000000, 5000000, 3000000) },
	SPRFMO		: { type: 'M', style: 'rfb_marine_noborder', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-19600000, -3200000), zoomExtent: new OpenLayers.Bounds(-12000000, -9000000, 5000000, 3000000) },
	SRFC		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-15, 15), zoomExtent: new OpenLayers.Bounds(-31, 0, -4, 31) },
	SWIOFC		: { type: 'MA', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(55, -10), zoomExtent: new OpenLayers.Bounds(5, -50, 82, 30) },
	WCPFC		: { type: 'M', style: 'rfb_marine_border', srs: '3349', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-18400000, 1000000.0), zoomExtent: new OpenLayers.Bounds(-20037508.34, -20037508.34, 20037508.34, 20037508.34) },
	WECAFC		: { type: 'M', style: 'rfb_marine_noborder', srs: '4326', isMasked: true,  globalZoom: false, centerCoords: new OpenLayers.LonLat(-65, 20), zoomExtent: new OpenLayers.Bounds(-110, -40, -20, 55) }
*/
};


//SIOFA Temp Membership to restore in the list above when ratified
//"SIOFA":    ["Australia", "Comoros", "Cook Islands", "European Union", "France", "Kenya", "Madagascar", "Mauritius", "Mozambique", "New Zealand", "Seychelles"],
//SPRFMO Temp Membership to restore in the list above when ratified
//"SPRFMO":   ["Australia", "Belize", "Canada", "Chile", "China", "Colombia", "Cook Islands", "Cuba", "Denmark", "Ecuador", "EU", "Fiji", "France", "Indonesia", "Japan", "Kiribati", "Rep of Korea", "Malaysia", "Marshall islands", "Micronesia", "Nauru", "New Zealand", "Niue", "Palau", "Panama", "Papua New Guinea", "Peru", "Russian Federation", "Samoa", "Solomon Islands", "Tonga", "Tuvalu", "Ukraine", "United Kingdom", "United States of America", "Vanuatu", "Venezuela"],
//CACFAC Temp Membership to restore in the list above when ratified
//"CACFAC":	["Armenia", "Azerbaijan", "China", "Georgia", "Islamic Republic of Iran", "Kazakhstan", "Kyrgyzstan", "Russian Federation", "Tajikistan", "Turkey", "Turkmenistan", "Uzbekistan"],


var rfbLayerCountries = {
	APFIC		: ["AUS", "BGD", "KHM", "CHN", "FRA", "IND", "IDN", "JPN", "KOR", "MYS", "MMR", "NPL", "NZL", "PAK", "PHL", "LKA", "THA", "GBR", "USA", "VNM"],
	'BOBP-IGO'	: ["BGD", "IND", "MDV", "LKA"],
	CACFAC		: ["KGZ", "TJK", "ARM"],
	CCAMLR		: ["ARG", "AUS", 'BEL', "BRA", "CHL", 'DEU', "EUR",'ESP','FRA','GBR',"IND",'ITA',"JPN", "NAM", "NZL", "NOR",'POL',"CHN","KOR", "RUS",'SWE',"ZAF","UKR","USA", "URY"],
	CCBSP		: ["CHN", "JPN", "KOR", "POL", "RUS", "USA"],
	CCSBT		: ["AUS", "IDN", "JPN", "NZL", "KOR"],
	CECAF		: ["AGO", "BEN", "CMR", "CPV", "COD", "COG", "CIV", "CUB", "GNQ", "EUR","GAB", "GMB", "GHA","GIN", "GNB","JPN", "KOR", "LBR", "MRT", "MAR","NGA", "NOR","STP", "SEN", "SLE","TGO", "USA"],
	CIFAA		: ["BEN", "BWA", "BFA", "BDI", "CMR", "CAF", "TCD", "COD", "COG", "CIV", "EGY", "ERI", "ETH", "GAB", "GMB", "GHA", "GIN", "KEN", "LSO", "MDG", "MWI", "MLI", "MUS", "MOZ", "NER", "NGA", "RWA", "SEN", "SLE", "SOM", "SDN", "SWZ", "TZA", "TGO", "UGA", "ZMB", "ZWE"],
	COMHAFAT	: ["MAR", "MRT", "CPV", "SEN", "GMB", "GNB", "GIN", "SLE", "LBR", "CIV", "GHA", "TGO", "BEN", "STP", "NGA", "CMR", "GNQ", "GAB", "COD", "COG", "AGO", "NAM"],
	COPESCAL	: ["ARG", "BOL", "BRA", "CHL", "COL", "CRI", "CUB", "DOM", "ECU", "SLV", "GTM", "HND", "JAM", "MEX", "NIC", "PAN", "PRY", "PER", "SUR", "URY", "VEN"],
	COREP		: ["CMR","COG","COD","GAB","STP"],
	CPPS		: ["CHL", "COL", "ECU", "PER"],
	CRFM		: ["AIA", "ATG", "BHS", "BRB", "BLZ", "DMA", "GRD", "GUY", "HTI", "JAM", "MSR", "KNA", "LCA", "VCT", "SUR", "TTO", "TCA"],
	CTMFM		: ["ARG", "URY"],
	EIFAAC		: ["BIH", "ALB", "HRV", "CYP", "EUR", "ISL", "ISR", "LUX", "NOR", "CHE", "TUR"],
	FCWC		: ["BEN", "CIV", "GHA", "LBR", "NGA", "TGO"],
	FFA		: ["AUS", "COK", "FSM", "FJI", "KIR", "MHL", "NRU", "NZL", "NIU", "PLW", "PNG", "WSM", "SLB", "TKL", "TON", "TUV", "VUT"],
	GFCM		: ["ALB", "DZA", "BGR", "HRV", "CYP", "EUR", "EGY", "ISR", "JPN", "LBN", "LBY", "MNE", "MLT", "MCO", "MAR", "ROU", "SYR", "SVN", "TUN", "TUR"],
	IATTC		: ["COL", "CRI", "ECU", "SLV", "FRA", "GTM", "JPN", "MEX", "NIC", "PAN", "PER", "KOR", "ESP", "USA", "VUT", "VEN"],
	ICCAT		: ["ALB", "DZA", "AGO", "BRB", "BLZ", "BRA", "CAN", "CPV", "CHN", "CIV", "HRV", "EGY", "GNQ", "EUR", "GAB", "GHA", "GTM", "GIN", "HND", "ISL", "JPN", "LBY", "MAR", "MRT", "MEX", "NAM", "NIC", "NGA", "NOR", "PAN", "PHL", "KOR", "RUS","VCT", "STP", "SEN", "SLE", "SPM", "ZAF", "SYR", "TTO", "TUN", "TUR", "UKX", "USA", "URY", "VUT", "VEN"],
	ICES		: ["BEL", "CAN", "DNK", "EST", "FIN", "FRA", "DEU", "ISL", "IRL", "LVA", "LTU", "NLD", "NOR", "POL", "PRT", "RUS", "ESP", "SWE", "GBR", "USA"],
	IOTC		: ["AUS", "BLZ", "CHN", "COM", "ERI", "EUR","GIN", "IND", "IDN", "IRN", "JPN", "KEN", "MDG", "MYS", "MUS", "OMN", "PAK", "PHL", "KOR", "SYC", "SLE", "LKA", "SDN", "THA","TZA", "VUT"],
	IPHC		: ["CAN", "USA"],
	IWC			: ["ATG", "ARG", "AUS", "AUT", "BEL", "BLZ", "BEN", "BRA", "BGR", "KHM", "CMR", "CHL", "CHN", "COG", "CRI", "CIV", "HRV", "CYP", "CZE", "DNK", "DMA", "DOM", "ECU", "ERI", "EST", "FIN", "FRA", "GAB", "GMB", "DEU", "GHA", "GRC", "GRD", "GTM", "GIN", "GNB", "HUN", "ISL", "IND", "IRL", "ITA", "JPN", "KEN", "KIR", "LAO", "LTU", "LUX", "MLI", "MHL", "MRT", "MEX", "MCO", "MAR", "NRU", "NLD", "NZL", "NIC", "NOR", "OMN", "PLW", "PAN", "POL", "PER", "PRT", "KOR", "ROU", "RUS", "KNA", "LCA", "VCT", "SMR", "SEN", "SVK", "SVN", "SLB", "ZAF", "ESP", "SUR", "SWE", "CHE", "TZA", "TGO", "TUV", "GBR", "USA", "URY"],
	LVFO		: ["UGA", "TZA", "KEN"],
	MRC		: ["KHM", "LAO", "THA", "VNM"],
	NAFO		: ["CAN", "CUB", "EUR", "SPM", "ISL", "JPN", "NOR", "KOR", "RUS", "UKR", "USA", "GRL", "FRO"],
	NAMMCO		: ["FRO", "GRL", "ISL", "NOR"],
	NASCO		: ["CAN", "EUR", "FRO", "GRL", "ISL", "NOR", "RUS", "USA"],
	NEAFC		: ["EUR", "ISL", "NOR", "RUS", "GRL", "FRO"],
	NPAFC		: ["CAN", "JPN", "KOR", "RUS", "USA"],
	OLDEPESCA	: ["BLZ", "BOL", "CRI", "CUB", "ECU", "SLV", "GUY", "HND", "MEX", "NIC", "PER", "VEN"],
	OSPESCA		: ["BLZ", "GTM", "SLV", "HND", "NIC", "CRI", "PAN"],
	PICES		: ["CAN", "CHN", "JPN", "KOR", "RUS", "USA"],
	PSC		: ["CAN", "USA"],
	RECOFI		: ["BHR", "IRQ", "IRN", "KWT", "OMN", "QAT", "SAU", "ARE"],
	SEAFDEC		: ["BRN", "KHM", "IDN", "JPN", "LAO", "MYS", "MMR", "PHL", "SGP", "THA", "VNM"],
	SEAFO		: ["AGO", "EUR", "NAM", "NOR"],
	SIOFA		: [],
	SPC		: ["AUS", "ASM", "COK", "FRA", "FSM", "FJI", "PYF", "GUM", "KIR", "MHL", "NRU", "NCL", "NIU", "NZL", "MNP", "PLW", "PNG", "PCN", "WSM", "SLB", "TKL", "TON", "TUV", "VUT", "WLF", "USA"],
	SPRFMO		: [],
	SRFC		: ["CPV", "GMB", "GIN", "GNB", "MRT", "SEN", "SLE"],
	SWIOFC		: ["COM", "FRA", "KEN", "MDG", "MDV", "MUS", "MOZ", "SYC", "SOM", "ZAF", "TZA", "YEM"],
	WCPFC		: ["AUS", "CAN", "CHN", "COK", "ECU", "FSM", "FJI", "FRA", "IDN", "JPN", "KIR", "MHL", "NRU", "NZL", "NIU", "PLW", "PNG", "PHL", "KOR", "WSM", "SLB", "TWN", "TON", "TUV", "USA", "VUT"],
	WECAFC		: ["ATG", "BHS", "BRB", "BLZ", "BRA", "CAN", "COL", "CRI", "CUB", "DMA", "DOM", "EUR","GRD", "GTM", "GIN", "GUY", "HTI", "HND", "JAM", "JPN", "KOR", "MEX","NIC", "PAN", "KNA", "LCA", "VCT","SUR", "TTO", "USA", "VEN"]
};


//SIOFA temp membership to restore in the list above when ratified
//"SIOFA":    ["AUS", "COM", "COK", "EUR", "FRA", "KEN", "MDG", "MUS", "MOZ", "NZL", "SYC"],
//SPRFMO temp membership to restore in the list above when ratified
//"SPRFMO":   ["AUS", "BLZ", "CAN", "CHL", "CHN", "COL", "COK", "CUB","ECU", "EUR", "FJI","IDN", "JPN", "KIR", "KOR", "MYS", "MHL", "FSM", "NRU", "NZL", "NIU", "PLW", "PAN", "PNG", "PER", "RUS", "WSM", "SLB", "TON", "TUV", "UKR","USA", "VUT", "VEN"],
//CACFAC temp membership to restore in the list above when ratified
//"CACFAC":	["ARM", "AZE", "CHN", "GEO", "IRN", "KAZ", "KGZ", "RUS", "TJK", "TUR", "TKM", "UZB"],

var rfbLayerDescriptors = {
	APFIC		: { link:"http://www.fao.org/fishery/rfb/apfic/en", title:"Asia-Pacific Fishery Commission (APFIC)" },
	'BOBP-IGO'	: { link:"http://www.fao.org/fishery/rfb/bobp_igo/en", title:"Bay of Bengal Programme Inter-Governmental Organization (BOBP-IGO)" },
	CACFAC		: { link:"http://www.fao.org/fishery/rfb/cacfac/en", title:"Central Asian and Caucasus Regional Fisheries and Aquaculture Commission (CACFAC)" },
	CCAMLR		: { link:"http://www.fao.org/fishery/rfb/ccamlr/en", title:"Commission on the Conservation of Antarctic Marine Living Resources (CCAMLR)" },
	CCBSP		: { link:"http://www.fao.org/fishery/rfb/ccbsp/en", title:"Convention on the Conservation and Management of Pollock Resources in the Central Bering Sea (CCBSP)" },
	CCSBT		: { link:"http://www.fao.org/fishery/rfb/ccsbt/en", title:"Commission for the Conservation of Southern Bluefin Tuna (CCSBT)" },
	CECAF		: { link:"http://www.fao.org/fishery/rfb/cecaf/en", title:"Fishery Committee for the Eastern Central Atlantic (CECAF)" },
	CIFAA		: { link:"http://www.fao.org/fishery/rfb/cifaa/en", title:"Committee for Inland Fisheries and Aquaculture of Africa (CIFAA)" },
	COMHAFAT	: { link:"http://www.atlafco.org", title:"Conference Ministerielle sur la Cooperation Halieutique entre les Etats Africains Riverains de l'ocean atlantique (COMHAFAT)" },
	COPESCAL	: { link:"http://www.fao.org/fishery/rfb/copescal/en", title:"Commission for Inland Fisheries of Latin America (COPESCAL)" },
	COREP		: { link:"http://www.fao.org/fishery/rfb/corep/en", title:"Regional Fisheries Committee for the Gulf of Guinea (COREP)" },
	CPPS		: { link:"http://www.fao.org/fishery/rfb/cpps/en", title:"Permanent Commission for the South Pacific (CPPS)" },
	CRFM		: { link:"http://www.fao.org/fishery/rfb/crfm/en", title:"Caribbean Regional Fisheries Mechanism (CRFM)" },
	CTMFM		: { link:"http://www.fao.org/fishery/rfb/ctmfm/en", title:"Joint Technical Commission for the Argentine-Uruguay Maritime Front (CTMFM)" },
	EIFAAC		: { link:"http://www.fao.org/fishery/rfb/eifaac/en", title:"European Inland Fisheries and Aquaculture Advisory Commission (EIFAAC)" },
	FCWC		: { link:"http://www.fao.org/fishery/rfb/fcwc/en", title:"Fishery Committee of the West Central Gulf of Guinea (FCWC)" },
	FFA		: { link:"http://www.fao.org/fishery/rfb/ffa/en", title:"Forum Fisheries Agency (FFA)" },
	GFCM		: { link:"http://www.gfcm.org/gfcm/about/en", title:"General Fisheries Commission for the Mediterranean (GFCM)" },
	IATTC		: { link:"http://www.fao.org/fishery/rfb/iattc/en", title:"INTER-AMERICAN Tropical Tuna Commission (IATTC)" },
	ICCAT		: { link:"http://www.fao.org/fishery/rfb/iccat/en", title:"International Commission for the Conservation of Atlantic Tunas (ICCAT)" },
	ICES		: { link:"http://www.fao.org/fishery/rfb/ices/en", title:"International Council for the Exploration of the Sea (ICES)" },
	IOTC		: { link:"http://www.fao.org/fishery/rfb/iotc/en", title:"Indian Ocean Tuna Commission (IOTC)" },
	IPHC		: { link:"http://www.fao.org/fishery/rfb/iphc/en", title:"International Pacific Halibut Commission (IPHC)" },
	IWC		: { link:"http://www.fao.org/fishery/rfb/iwc/en", title:"International Whaling Commission (IWC)" },
	LVFO		: { link:"http://www.fao.org/fishery/rfb/lvfo/en", title:"Lake Victoria Fisheries Organization (LVFO)" },
	MRC		: { link:"http://www.fao.org/fishery/rfb/mrc/en", title:"Mekong River Commission (MRC)" },
	NAFO		: { link:"http://www.fao.org/fishery/rfb/nafo/en", title:"Northwest Atlantic Fisheries Organization (NAFO)" },
	NAMMCO		: { link:"http://www.fao.org/fishery/rfb/nammco/en", title:"North Atlantic Marine Mammal Commission (NAMMCO)" },
	NASCO		: { link:"http://www.fao.org/fishery/rfb/nasco/en", title:"North Atlantic Salmon Conservation Organization (NASCO)" },
	NEAFC		: { link:"http://www.fao.org/fishery/rfb/neafc/en", title:"North East Atlantic Fisheries Commission (NEAFC)" },
	NPAFC		: { link:"http://www.fao.org/fishery/rfb/npafc/en", title:"North Pacific Anadromous Fish Commission (NPAFC)" },
	OLDEPESCA	: { link:"http://www.fao.org/fishery/rfb/oldepesca/en", title:"Latin American Organization for Fisheries Development (OLDEPESCA)" },
	OSPESCA		: { link:"http://www.sica.int/ospesca/", title:"Organizacion del Sector Pesquero y Acuicola del Istmo Centroamericano (OSPESCA)" },
	PICES		: { link:"http://www.fao.org/fishery/rfb/pices/en", title:"The North Pacific Marine Science Organization (PICES)" },
	PSC		: { link:"http://www.fao.org/fishery/rfb/psc/en", title:"Pacific Salmon Commission (PSC)" },
	RECOFI		: { link:"http://www.fao.org/fishery/rfb/recofi/en", title:"Regional Commission for Fisheries (RECOFI)" },
	SEAFDEC		: { link:"http://www.fao.org/fishery/rfb/seafdec/en", title:"Southeast Asian Fisheries Development Center (SEAFDEC)" },
	SEAFO		: { link:"http://www.fao.org/fishery/rfb/seafo/en", title:"Southeast Atlantic Fisheries Organization (SEAFO)" },
	SIOFA		: { link:"http://www.fao.org/fishery/rfb/siofa/en", title:"South Indian Ocean Fisheries Agreement (SIOFA)" },
	SPC		: { link:"http://www.fao.org/fishery/rfb/spc/en", title:"Secretariat Of The Pacific Community (SPC)" },
	SPRFMO		: { link:"http://www.southpacificrfmo.org/", title:"South Pacific Regional Fisheries Management Organisation (SPRFMO)" },
	SRFC		: { link:"http://www.fao.org/fishery/rfb/srfc/en", title:"Subregional Fisheries Commission (SRFC)" },
	SWIOFC		: { link:"http://www.fao.org/fishery/rfb/swiofc/en", title:"Southwest Indian Ocean Fisheries Commission (SWIOFC)" },
	WCPFC		: { link:"http://www.fao.org/fishery/rfb/wcpfc/en", title:"Western and Central Pacific Fisheries Commission (WCPFC)" },
	WECAFC		: { link:"http://www.fao.org/fishery/rfb/wecafc/en", title:"Western Central Atlantic Fishery Commission (WECAFC)" }
};

var staticLabels = {
	'(NO SPECIES SELECTED)'	: { en: '(No species selected)' },
	'200 NMI ARCS'		: '200 nmi arcs',
	'FAO FISHING AREAS'	: { en:'FAO fishing areas', fr:'Zones de pêche de la FAO'},
	'ALL FAO AREAS'		: { en:'FAO areas and their sub-divisions' },
	'COORDINATES GRID'	: { en:'Coordinates Grid' },
	FAO_DIV			: { en:'FAO divisions'},
	FAO_MAJOR		: { en:'FAO major fishing areas', fr:'Principales zones de pêche de la FAO'},
	FAO_SUB_AREA		: { en:'FAO sub areas'},
	FAO_SUB_DIV		: { en:'FAO sub divisions'},
	GFCM_SUB_AREA		: { en:'GFCM geographical sub-areas'},
	ICCAT_SMU		: { en:'ICCAT management unit'},
	INTERSECTING		: { en:'Intersecting: ', fr:'Intersection :'},
	MEMBERS			: 'Members',
	COUNTRY_BOUNDS		: 'Countries - Union of countries',
	PAC_TUNA_REP		: { en:'Pacific tuna reporting area'},
	RFB_COMP		: { en:'RFB Area of competence', fr:'Zone de compétence du ORP'},
	RFB_MARINE_NOBORDER	: { en:'Area of competence'},
	RFB_INLAND_NOBORDER	: { en:'Area of competence'},
	RFB_UNSPECIFIED_NOBORDER: { en:"Area of competence without specified limits"},
	SPECIES_DIST		: { en:'Species distribution'},
	COUNTRY_ISO3_AGO	: { en:"Angola"},
	COUNTRY_ISO3_AIA	: { en:"Anguilla"},
	COUNTRY_ISO3_ALB	: { en:"Albania"},
	COUNTRY_ISO3_DZA	: { en:"Algeria"},
	COUNTRY_ISO3_AUT	: { en:"Austria"},
	COUNTRY_ISO3_ARE	: { en:"United Arab Emirates"},
	COUNTRY_ISO3_ARG	: { en:"Argentina"},
	COUNTRY_ISO3_ARM	: { en:"Tajikistan"},
	COUNTRY_ISO3_ASM	: { en:"American Samoa"},
	COUNTRY_ISO3_ATG	: { en:"Antigua and Barbuda"},
	COUNTRY_ISO3_AUS	: { en:"Australia"},
	COUNTRY_ISO3_BDI	: { en:"Burundi"},
	COUNTRY_ISO3_BEL	: { en:"Belgium"},
	COUNTRY_ISO3_BEN	: { en:"Benin"},
	COUNTRY_ISO3_BFA	: { en:"Burkina Faso"},
	COUNTRY_ISO3_BGD	: { en:"Bangladesh"},
	COUNTRY_ISO3_BHR	: { en:"Bahrain"},
	COUNTRY_ISO3_BHS	: { en:"Bahamas"},
	COUNTRY_ISO3_BLR	: { en:"Belarus"},
	COUNTRY_ISO3_BLZ	: { en:"Belize"},
	COUNTRY_ISO3_BOL	: { en:"Bolivia"},
	COUNTRY_ISO3_BRA	: { en:"Brazil"},
	COUNTRY_ISO3_BRB	: { en:"Barbados"},
	COUNTRY_ISO3_BRN	: { en:"Brunei Darussalam"},
	COUNTRY_ISO3_BWA	: { en:"Botswana"},
	COUNTRY_ISO3_BIH	: { en:"Bosnia and Herzegovina"},
	COUNTRY_ISO3_BGR	: { en:"Bulgaria"},
	COUNTRY_ISO3_CAF	: { en:"Central Africa Rep"},
	COUNTRY_ISO3_CAN	: { en:"Canada"},
	COUNTRY_ISO3_CHL	: { en:"Chile"},
	COUNTRY_ISO3_CHN	: { en:"China"},
	COUNTRY_ISO3_CIV	: { en:"Côte D'Ivoire"},
	COUNTRY_ISO3_CMR	: { en:"Cameroon"},
	COUNTRY_ISO3_COD	: { en:"Dem Rep of Congo"},
	COUNTRY_ISO3_COG	: { en:"Congo"},
	COUNTRY_ISO3_COK	: { en:"Cook Islands"},
	COUNTRY_ISO3_COL	: { en:"Colombia"},
	COUNTRY_ISO3_COM	: { en:"Comoros"},
	COUNTRY_ISO3_CPV	: { en:"Cape Verde"},
	COUNTRY_ISO3_CRI	: { en:"Costa Rica"},
	COUNTRY_ISO3_HRV	: { en:"Croatia"},
	COUNTRY_ISO3_CUB	: { en:"Cuba"},
	COUNTRY_ISO3_CYP	: { en:"Cyprus"},
	COUNTRY_ISO3_CZE	: { en:"Czech Republic"},
	COUNTRY_ISO3_DEU	: { en:"Germany"},
	COUNTRY_ISO3_DMA	: { en:"Dominica"},
	COUNTRY_ISO3_DNK	: { en:"Denmark"},
	COUNTRY_ISO3_DOM	: { en:"Dominican Rep"},
	COUNTRY_ISO3_ECU	: { en:"Ecuador"},
	COUNTRY_ISO3_EGY	: { en:"Egypt"},
	COUNTRY_ISO3_ERI	: { en:"Eritrea"},
	COUNTRY_ISO3_ESP	: { en:"Spain"},
	COUNTRY_ISO3_EST	: { en:"Estonia"},
	COUNTRY_ISO3_ETH	: { en:"Ethiopia"},
	COUNTRY_ISO3_EUR	: { en:"EU"},
	COUNTRY_ISO3_FIN	: { en:"Finland"},
	COUNTRY_ISO3_FJI	: { en:"Fiji"},
	COUNTRY_ISO3_FRA	: { en:"France"},
	COUNTRY_ISO3_FRO	: { en:"Faroe Islands (Denmark)"},
	COUNTRY_ISO3_FSM	: { en:"Micronesia"},
	COUNTRY_ISO3_GAB	: { en:"Gabon"},
	COUNTRY_ISO3_GBR	: { en:"United Kingdom"},
	COUNTRY_ISO3_GHA	: { en:"Ghana"},
	COUNTRY_ISO3_GIN	: { en:"Guinea"},
	COUNTRY_ISO3_GMB	: { en:"Gambia"},
	COUNTRY_ISO3_GNB	: { en:"Guinea-Bissau"},
	COUNTRY_ISO3_GNQ	: { en:"Equatorial Guinea"},
	COUNTRY_ISO3_GRC	: { en:"Greece"},
	COUNTRY_ISO3_GRD	: { en:"Grenada"},
	COUNTRY_ISO3_GRL	: { en:"Greenland (Denmark)"},
	COUNTRY_ISO3_GTM	: { en:"Guatemala"},
	COUNTRY_ISO3_GUF	: { en:"French Guiana"},
	COUNTRY_ISO3_GUM	: { en:"Guam"},
	COUNTRY_ISO3_GUY	: { en:"Guyana"},
	COUNTRY_ISO3_HND	: { en:"Honduras"},
	COUNTRY_ISO3_HTI	: { en:"Haiti"},
	COUNTRY_ISO3_HUN	: { en:"Hungary"},
	COUNTRY_ISO3_IDN	: { en:"Indonesia"},
	COUNTRY_ISO3_IND	: { en:"India"},
	COUNTRY_ISO3_IRL	: { en:"Ireland"},
	COUNTRY_ISO3_IRN	: { en:"Islamic Republic of Iran"},
	COUNTRY_ISO3_IRQ	: { en:"Iraq"},
	COUNTRY_ISO3_ISL	: { en:"Iceland"},
	COUNTRY_ISO3_ISR	: { en:"Israel"},
	COUNTRY_ISO3_ITA	: { en:"Italy"},
	COUNTRY_ISO3_JAM	: { en:"Jamaica"},
	COUNTRY_ISO3_JPN	: { en:"Japan"},
	COUNTRY_ISO3_KEN	: { en:"Kenya"},
	COUNTRY_ISO3_KGZ	: { en:"Armenia"},
	COUNTRY_ISO3_KHM	: { en:"Cambodia"},
	COUNTRY_ISO3_KIR	: { en:"Kiribati"},
	COUNTRY_ISO3_KNA	: { en:"Saint Kitts and Nevis"},
	COUNTRY_ISO3_KOR	: { en:"Rep of Korea"},
	COUNTRY_ISO3_KWT	: { en:"Kuwait"},
	COUNTRY_ISO3_LAO	: { en:"Lao People Dem Rep"},
	COUNTRY_ISO3_LBR	: { en:"Liberia"},
	COUNTRY_ISO3_LCA	: { en:"Saint Lucia"},
	COUNTRY_ISO3_LKA	: { en:"Sri Lanka"},
	COUNTRY_ISO3_LBN	: { en:"Lebanon"},
	COUNTRY_ISO3_LSO	: { en:"Lesotho"},
	COUNTRY_ISO3_LTU	: { en:"Lithuania"},
	COUNTRY_ISO3_LUX	: { en:"Luxembourg"},
	COUNTRY_ISO3_LVA	: { en:"Latvia"},
	COUNTRY_ISO3_LBY	: { en:"Libyan Arab Jamahiriya"},
	COUNTRY_ISO3_MAR	: { en:"Morocco"},
	COUNTRY_ISO3_MDG	: { en:"Madagascar"},
	COUNTRY_ISO3_MDV	: { en:"Maldives"},
	COUNTRY_ISO3_MEX	: { en:"Mexico"},
	COUNTRY_ISO3_MHL	: { en:"Marshall islands"},
	COUNTRY_ISO3_MLI	: { en:"Mali"},
	COUNTRY_ISO3_MMR	: { en:"Myanmar"},
	COUNTRY_ISO3_MNP	: { en:"Northern Mariana Islands"},
	COUNTRY_ISO3_MOZ	: { en:"Mozambique"},
	COUNTRY_ISO3_MRT	: { en:"Mauritania"},
	COUNTRY_ISO3_MSR	: { en:"Montserrat"},
	COUNTRY_ISO3_MNG	: { en:"Mongolia"},
	COUNTRY_ISO3_MNE	: { en:"Montenegro"},
	COUNTRY_ISO3_MCO	: { en:"Monaco"},
	COUNTRY_ISO3_MUS	: { en:"Mauritius"},
	COUNTRY_ISO3_MWI	: { en:"Malawi"},
	COUNTRY_ISO3_MYS	: { en:"Malaysia"},
	COUNTRY_ISO3_NAM	: { en:"Namibia"},
	COUNTRY_ISO3_NCL	: { en:"New Caledonia"},
	COUNTRY_ISO3_NER	: { en:"Niger"},
	COUNTRY_ISO3_NGA	: { en:"Nigeria"},
	COUNTRY_ISO3_NIC	: { en:"Nicaragua"},
	COUNTRY_ISO3_NIU	: { en:"Niue"},
	COUNTRY_ISO3_NLD	: { en:"Netherlands"},
	COUNTRY_ISO3_NOR	: { en:"Norway"},
	COUNTRY_ISO3_NPL	: { en:"Nepal"},
	COUNTRY_ISO3_NRU	: { en:"Nauru"},
	COUNTRY_ISO3_NZL	: { en:"New Zealand"},
	COUNTRY_ISO3_OMN	: { en:"Oman"},
	COUNTRY_ISO3_PAK	: { en:"Pakistan"},
	COUNTRY_ISO3_PAN	: { en:"Panama"},
	COUNTRY_ISO3_PCN	: { en:"Pitcairn Island"},
	COUNTRY_ISO3_PER	: { en:"Peru"},
	COUNTRY_ISO3_PHL	: { en:"Philippines"},
	COUNTRY_ISO3_PLW	: { en:"Palau"},
	COUNTRY_ISO3_PNG	: { en:"Papua New Guinea"},
	COUNTRY_ISO3_POL	: { en:"Poland"},
	COUNTRY_ISO3_PRT	: { en:"Portugal"},
	COUNTRY_ISO3_PRY	: { en:"Paraguay"},
	COUNTRY_ISO3_PYF	: { en:"French Polynesia"},
	COUNTRY_ISO3_QAT	: { en:"Qatar"},
	COUNTRY_ISO3_ROU	: { en:"Romania"},
	COUNTRY_ISO3_RUS	: { en:"Russian Federation"},
	COUNTRY_ISO3_RWA	: { en:"Rwanda"},
	COUNTRY_ISO3_SAU	: { en:"Saudi Arabia"},
	COUNTRY_ISO3_SDN	: { en:"Sudan"},
	COUNTRY_ISO3_SEN	: { en:"Senegal"},
	COUNTRY_ISO3_SGP	: { en:"Singapore"},
	COUNTRY_ISO3_SLB	: { en:"Solomon Islands"},
	COUNTRY_ISO3_SLE	: { en:"Sierra Leone"},
	COUNTRY_ISO3_SLV	: { en:"El Salvador"},
	COUNTRY_ISO3_SMR	: { en:"San Marino"},
	COUNTRY_ISO3_SOM	: { en:"Somalia"},
	COUNTRY_ISO3_SPM	: { en:"France (in relation to Saint Pierre and Miquelon)"},
	COUNTRY_ISO3_STP	: { en:"Sao Tome And Principe"},
	COUNTRY_ISO3_SLE	: { en:"Sierra Leone"},
	COUNTRY_ISO3_SUR	: { en:"Suriname"},
	COUNTRY_ISO3_SWE	: { en:"Sweden"},
	COUNTRY_ISO3_SWZ	: { en:"Swaziland"},
	COUNTRY_ISO3_SVK	: { en:"Slovakia"},
	COUNTRY_ISO3_SVN	: { en:"Slovenia"},
	COUNTRY_ISO3_SLB	: { en:"Solomon Islands"},
	COUNTRY_ISO3_CHE	: { en:"Switzerland"},
	COUNTRY_ISO3_SYC	: { en:"Seychelles"},
	COUNTRY_ISO3_SYR	: { en:"Syrian Arab Republic"},
	COUNTRY_ISO3_TCA	: { en:"Turks and Caicos Islands"},
	COUNTRY_ISO3_TCD	: { en:"Chad"},
	COUNTRY_ISO3_TGO	: { en:"Togo"},
	COUNTRY_ISO3_THA	: { en:"Thailand"},
	COUNTRY_ISO3_TJK	: { en:"Kyrgyzstan"},
	COUNTRY_ISO3_TKL	: { en:"Tokelau"},
	COUNTRY_ISO3_TON	: { en:"Tonga"},
	COUNTRY_ISO3_TTO	: { en:"Trinidad and Tobago"},
	COUNTRY_ISO3_TUV	: { en:"Tuvalu"},
	COUNTRY_ISO3_TUN	: { en:"Tunisia"},
	COUNTRY_ISO3_TUR	: { en:"Turkey"},
	COUNTRY_ISO3_TWN	: { en:"Taiwan Province of China"},
	COUNTRY_ISO3_UKX	: { en:"United Kingdom (in relation to Other Territories)"},
	COUNTRY_ISO3_TZA	: { en:"United Rep of Tanzania"},
	COUNTRY_ISO3_UGA	: { en:"Uganda"},
	COUNTRY_ISO3_UKR	: { en:"Ukraine"},
	COUNTRY_ISO3_URY	: { en:"Uruguay"},
	COUNTRY_ISO3_USA	: { en:"United States of America"},
	COUNTRY_ISO3_VCT	: { en:"Saint Vincent and the Grenadines"},
	COUNTRY_ISO3_VGB	: { en:"British Virgin Islands (UK)"},
	COUNTRY_ISO3_VEN	: { en:"Venezuela"},
	COUNTRY_ISO3_VNM	: { en:"Viet Nam"},
	COUNTRY_ISO3_VUT	: { en:"Vanuatu"},
	COUNTRY_ISO3_WLF	: { en:"Wallis and Futuna"},
	COUNTRY_ISO3_WSM	: { en:"Samoa"},
	COUNTRY_ISO3_YEM	: { en:"Yemen"},
	COUNTRY_ISO3_ZAF	: { en:"South Africa"},
	COUNTRY_ISO3_ZMB	: { en:"Zambia"},
	COUNTRY_ISO3_ZWE	: { en:"Zimbabwe"},
	//SIDE PANEL
	SIDP_MAP			: {en:"Map"},
	SIDP_LAYERS			: {en:"Layers"},
	SIDP_LEGEND			: {en:"Legend"},
	SIDP_SEARCH			: {en:"Search"},
	SIDP_CLEAR			: {en:"Clear"},
	SIDP_NOGEOMETRY     : {en:"Area isn't defined yet!"},    
	SIDP_NOFEATURES     : {en:"The server did not return any feature !"},
    //ZOOMTO RFB LABELS
    ZOOMTO_RFB_LBL		: {en:"RFB ZoomTo"},
    //ZOOMTO RFB EMPTY
    ZOOMTO_RFB_EMP		: {en:"Select RFB..."},
    // SEARCH NO RESULT LABEL
    ZOOMTO_NO_RES		: {en:'RFB not found'},
    ZOOMTO_LOADING		: {en:'Loading'},
	//SEARCH FIELDS LABELS
	SEARCH_TEXT_LBL		: {en:"Free text search"},
	SEARCH_RFMO_LBL		: {en:"By Management Body/Authority(ies)"},
	SEARCH_TYPE_LBL		: {en:"By Area Type"},
	SEARCH_STAT_LBL		: {en:"By Status"},
	SEARCH_CRIT_LBL		: {en:"By VME Criteria"},
	SEARCH_YEAR_LBL		: {en:"By Year"},
	//SEARCH EMPTY TEXT
	SEARCH_TEXT_EMP		: {en:"Free text"},
	SEARCH_RFMO_EMP		: {en:"Select..."},
	SEARCH_TYPE_EMP		: {en:"Select..."},
	SEARCH_STAT_EMP		: {en:"Select..."},
	SEARCH_CRIT_EMP		: {en:"Select..."},
	SEARCH_YEAR_EMP		: {en:"Select..."},
	// SEARCH NO RESULT LABEL
	SEARCH_NO_RES		: {en:'Nothing to display'},
	SEARCH_LOADING		: {en:'Loading'},
	SEARCH_BACK_FORM	: {en:'&laquo; Back to search'},
	//VME AREA TYPES
	VME_TYPE_VME		: { en:"VME"},
	VME_TYPE_RISK		: { en:"Risk Area"},
	VME_TYPE_BPA		: { en:"Benthic protected area"},
	VME_TYPE_CLOSED		: { en:"Closed area"},
	VME_TYPE_OTHER		: { en:"Other types of managed areas"},
	//VME STATUSES 
	VME_STATUS_RSK		: { en:"Risk"},
	VME_STATUS_ENS		: { en:"Established"},
	VME_STATUS_UNDEST	: { en:"Under establishment"},
	VME_STATUS_VOL		: { en:"Voluntary"},
	VME_STATUS_EXP		: { en:"Exploratory"},
	VME_STATUS_POT		: { en:"Potential"},
	VME_STATUS_TEMP		: { en:"Temporary"},
	//VME CRITERIA 
	VME_CRITERIA_UNIQUE	: { en:"Uniqueness or rarity"},
	VME_CRITERIA_FUNCT	: { en:"Functional significance of the habitat"},
	VME_CRITERIA_FRAG	: { en:"Fragility"},
	VME_CRITERIA_LIFE	: { en:"Life-history traits"},
	VME_CRITERIA_STRUCT	: { en:"Structural complexity"},
	VME_CRITERIA_NOTS	: { en:"Not specified"},
	
	//SUB_TITLE           : { en:"The Vulnerable Marine Ecosystems Database (VME-DB)<br />gathers information on VME areas stored in harmonized<br />way and disseminated through maps and fact sheets."},
	SUB_TITLE           : { en:"Global inventory of fisheries measures adopted in ABNJ <br />to prevent significant adverse impacts of high-seas <br />bottom fisheries on vulnerable marine ecosystems (VMEs) and associated information"},
	
	LEGEND_NOTE_SIOFA	: "The Agreement is subject to ratification, acceptance or approval by the signatories.<br />The signatories and the participants that have deposited their instruments can be found <a href=\"http://www.fao.org/Legal/treaties/035s-e.htm\" target=\"_blank\">here</a>.",
	LEGEND_NOTE_SPRFMO	: "The Convention is subject to ratification, acceptance or approval by the signatories<br />The signatories and the participants that have deposited their instruments can be found <a href=\"http://www.southpacificrfmo.org/status-of-the-convention\" target=\"_blank\">here</a>.",
	LEGEND_NOTE_CACFAC	: "<br><i>In December 2009 the following countries were officially invited by the Director General to become member of the Commission: Armenia, Azerbaijan, People's Republic China, Georgia, Islamic Republic of Iran, Kazakhstan, Kyrgyzstan, Russian Federation, Tajikistan, Turkey, Turkmenistan, Uzbekistan, Afghanistan, Mongolia and Ukraine.</i>",
	SELECT_AN_RFB		: '(Select a competent authority)',
    SELECT_AN_AREA      : '(Select an area)',
	DISCLAIMER			: "<strong>Disclaimer:</strong> The designations employed and the presentation of material in the map(s) are for illustration only and do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers or boundaries.",
	defined			: true
};
