// unicode glyph:  - don't remove, needed for Windows bug

var VMELabels = new Object();


VMELabels.staticLabels = {
	'(NO SPECIES SELECTED)'	: { en: '(No species selected)' },
	'200 NMI ARCS'		: '200 nmi arcs',
	'FAO FISHING AREAS'	: { en:'FAO fishing areas', fr:'Zones de pêche de la FAO'},
	'ALL FAO AREAS'		: { en:'FAO areas and their sub-divisions' },
	'COORDINATES GRID'	: { en:'Coordinates Grid' },
	FAO_DIV			: { en:'FAO divisions'},
	FAO_MAJOR		: { en:'FAO major fishing areas', fr:'Principales zones de pêche de la FAO'},
	FAO_SUB_AREA		: { en:'FAO sub areas'},
	FAO_SUB_DIV		: { en:'FAO sub divisions'},
	GFCM_SUB_AREA		: { en:'GFCM geographical sub-areas'},
	ICCAT_SMU		: { en:'ICCAT management unit'},
	INTERSECTING		: { en:'Intersecting: ', fr:'Intersection :'},
	MEMBERS			: 'Members',
	COUNTRY_BOUNDS		: 'Countries - Union of countries',
	PAC_TUNA_REP		: { en:'Pacific tuna reporting area'},
	RFB_COMP		: { en:'RFB Area of competence', fr:'Zone de compétence du ORP'},
	RFB_MARINE_NOBORDER	: { en:'Area of competence'},
	RFB_INLAND_NOBORDER	: { en:'Area of competence'},
	RFB_UNSPECIFIED_NOBORDER: { en:"Area of competence without specified limits"},
	SPECIES_DIST		: { en:'Species distribution'},
	COUNTRY_ISO3_AGO	: { en:"Angola"},
	COUNTRY_ISO3_AIA	: { en:"Anguilla"},
	COUNTRY_ISO3_ALB	: { en:"Albania"},
	COUNTRY_ISO3_DZA	: { en:"Algeria"},
	COUNTRY_ISO3_AUT	: { en:"Austria"},
	COUNTRY_ISO3_ARE	: { en:"United Arab Emirates"},
	COUNTRY_ISO3_ARG	: { en:"Argentina"},
	COUNTRY_ISO3_ARM	: { en:"Tajikistan"},
	COUNTRY_ISO3_ASM	: { en:"American Samoa"},
	COUNTRY_ISO3_ATG	: { en:"Antigua and Barbuda"},
	COUNTRY_ISO3_AUS	: { en:"Australia"},
	COUNTRY_ISO3_BDI	: { en:"Burundi"},
	COUNTRY_ISO3_BEL	: { en:"Belgium"},
	COUNTRY_ISO3_BEN	: { en:"Benin"},
	COUNTRY_ISO3_BFA	: { en:"Burkina Faso"},
	COUNTRY_ISO3_BGD	: { en:"Bangladesh"},
	COUNTRY_ISO3_BHR	: { en:"Bahrain"},
	COUNTRY_ISO3_BHS	: { en:"Bahamas"},
	COUNTRY_ISO3_BLR	: { en:"Belarus"},
	COUNTRY_ISO3_BLZ	: { en:"Belize"},
	COUNTRY_ISO3_BOL	: { en:"Bolivia"},
	COUNTRY_ISO3_BRA	: { en:"Brazil"},
	COUNTRY_ISO3_BRB	: { en:"Barbados"},
	COUNTRY_ISO3_BRN	: { en:"Brunei Darussalam"},
	COUNTRY_ISO3_BWA	: { en:"Botswana"},
	COUNTRY_ISO3_BIH	: { en:"Bosnia and Herzegovina"},
	COUNTRY_ISO3_BGR	: { en:"Bulgaria"},
	COUNTRY_ISO3_CAF	: { en:"Central Africa Rep"},
	COUNTRY_ISO3_CAN	: { en:"Canada"},
	COUNTRY_ISO3_CHL	: { en:"Chile"},
	COUNTRY_ISO3_CHN	: { en:"China"},
	COUNTRY_ISO3_CIV	: { en:"Côte D'Ivoire"},
	COUNTRY_ISO3_CMR	: { en:"Cameroon"},
	COUNTRY_ISO3_COD	: { en:"Dem Rep of Congo"},
	COUNTRY_ISO3_COG	: { en:"Congo"},
	COUNTRY_ISO3_COK	: { en:"Cook Islands"},
	COUNTRY_ISO3_COL	: { en:"Colombia"},
	COUNTRY_ISO3_COM	: { en:"Comoros"},
	COUNTRY_ISO3_CPV	: { en:"Cape Verde"},
	COUNTRY_ISO3_CRI	: { en:"Costa Rica"},
	COUNTRY_ISO3_HRV	: { en:"Croatia"},
	COUNTRY_ISO3_CUB	: { en:"Cuba"},
	COUNTRY_ISO3_CYP	: { en:"Cyprus"},
	COUNTRY_ISO3_CZE	: { en:"Czech Republic"},
	COUNTRY_ISO3_DEU	: { en:"Germany"},
	COUNTRY_ISO3_DMA	: { en:"Dominica"},
	COUNTRY_ISO3_DNK	: { en:"Denmark"},
	COUNTRY_ISO3_DOM	: { en:"Dominican Rep"},
	COUNTRY_ISO3_ECU	: { en:"Ecuador"},
	COUNTRY_ISO3_EGY	: { en:"Egypt"},
	COUNTRY_ISO3_ERI	: { en:"Eritrea"},
	COUNTRY_ISO3_ESP	: { en:"Spain"},
	COUNTRY_ISO3_EST	: { en:"Estonia"},
	COUNTRY_ISO3_ETH	: { en:"Ethiopia"},
	COUNTRY_ISO3_EUR	: { en:"EU"},
	COUNTRY_ISO3_FIN	: { en:"Finland"},
	COUNTRY_ISO3_FJI	: { en:"Fiji"},
	COUNTRY_ISO3_FRA	: { en:"France"},
	COUNTRY_ISO3_FRO	: { en:"Faroe Islands (Denmark)"},
	COUNTRY_ISO3_FSM	: { en:"Micronesia"},
	COUNTRY_ISO3_GAB	: { en:"Gabon"},
	COUNTRY_ISO3_GBR	: { en:"United Kingdom"},
	COUNTRY_ISO3_GHA	: { en:"Ghana"},
	COUNTRY_ISO3_GIN	: { en:"Guinea"},
	COUNTRY_ISO3_GMB	: { en:"Gambia"},
	COUNTRY_ISO3_GNB	: { en:"Guinea-Bissau"},
	COUNTRY_ISO3_GNQ	: { en:"Equatorial Guinea"},
	COUNTRY_ISO3_GRC	: { en:"Greece"},
	COUNTRY_ISO3_GRD	: { en:"Grenada"},
	COUNTRY_ISO3_GRL	: { en:"Greenland (Denmark)"},
	COUNTRY_ISO3_GTM	: { en:"Guatemala"},
	COUNTRY_ISO3_GUF	: { en:"French Guiana"},
	COUNTRY_ISO3_GUM	: { en:"Guam"},
	COUNTRY_ISO3_GUY	: { en:"Guyana"},
	COUNTRY_ISO3_HND	: { en:"Honduras"},
	COUNTRY_ISO3_HTI	: { en:"Haiti"},
	COUNTRY_ISO3_HUN	: { en:"Hungary"},
	COUNTRY_ISO3_IDN	: { en:"Indonesia"},
	COUNTRY_ISO3_IND	: { en:"India"},
	COUNTRY_ISO3_IRL	: { en:"Ireland"},
	COUNTRY_ISO3_IRN	: { en:"Islamic Republic of Iran"},
	COUNTRY_ISO3_IRQ	: { en:"Iraq"},
	COUNTRY_ISO3_ISL	: { en:"Iceland"},
	COUNTRY_ISO3_ISR	: { en:"Israel"},
	COUNTRY_ISO3_ITA	: { en:"Italy"},
	COUNTRY_ISO3_JAM	: { en:"Jamaica"},
	COUNTRY_ISO3_JPN	: { en:"Japan"},
	COUNTRY_ISO3_KEN	: { en:"Kenya"},
	COUNTRY_ISO3_KGZ	: { en:"Armenia"},
	COUNTRY_ISO3_KHM	: { en:"Cambodia"},
	COUNTRY_ISO3_KIR	: { en:"Kiribati"},
	COUNTRY_ISO3_KNA	: { en:"Saint Kitts and Nevis"},
	COUNTRY_ISO3_KOR	: { en:"Rep of Korea"},
	COUNTRY_ISO3_KWT	: { en:"Kuwait"},
	COUNTRY_ISO3_LAO	: { en:"Lao People Dem Rep"},
	COUNTRY_ISO3_LBR	: { en:"Liberia"},
	COUNTRY_ISO3_LCA	: { en:"Saint Lucia"},
	COUNTRY_ISO3_LKA	: { en:"Sri Lanka"},
	COUNTRY_ISO3_LBN	: { en:"Lebanon"},
	COUNTRY_ISO3_LSO	: { en:"Lesotho"},
	COUNTRY_ISO3_LTU	: { en:"Lithuania"},
	COUNTRY_ISO3_LUX	: { en:"Luxembourg"},
	COUNTRY_ISO3_LVA	: { en:"Latvia"},
	COUNTRY_ISO3_LBY	: { en:"Libyan Arab Jamahiriya"},
	COUNTRY_ISO3_MAR	: { en:"Morocco"},
	COUNTRY_ISO3_MDG	: { en:"Madagascar"},
	COUNTRY_ISO3_MDV	: { en:"Maldives"},
	COUNTRY_ISO3_MEX	: { en:"Mexico"},
	COUNTRY_ISO3_MHL	: { en:"Marshall islands"},
	COUNTRY_ISO3_MLI	: { en:"Mali"},
	COUNTRY_ISO3_MMR	: { en:"Myanmar"},
	COUNTRY_ISO3_MNP	: { en:"Northern Mariana Islands"},
	COUNTRY_ISO3_MOZ	: { en:"Mozambique"},
	COUNTRY_ISO3_MRT	: { en:"Mauritania"},
	COUNTRY_ISO3_MSR	: { en:"Montserrat"},
	COUNTRY_ISO3_MNG	: { en:"Mongolia"},
	COUNTRY_ISO3_MNE	: { en:"Montenegro"},
	COUNTRY_ISO3_MCO	: { en:"Monaco"},
	COUNTRY_ISO3_MUS	: { en:"Mauritius"},
	COUNTRY_ISO3_MWI	: { en:"Malawi"},
	COUNTRY_ISO3_MYS	: { en:"Malaysia"},
	COUNTRY_ISO3_NAM	: { en:"Namibia"},
	COUNTRY_ISO3_NCL	: { en:"New Caledonia"},
	COUNTRY_ISO3_NER	: { en:"Niger"},
	COUNTRY_ISO3_NGA	: { en:"Nigeria"},
	COUNTRY_ISO3_NIC	: { en:"Nicaragua"},
	COUNTRY_ISO3_NIU	: { en:"Niue"},
	COUNTRY_ISO3_NLD	: { en:"Netherlands"},
	COUNTRY_ISO3_NOR	: { en:"Norway"},
	COUNTRY_ISO3_NPL	: { en:"Nepal"},
	COUNTRY_ISO3_NRU	: { en:"Nauru"},
	COUNTRY_ISO3_NZL	: { en:"New Zealand"},
	COUNTRY_ISO3_OMN	: { en:"Oman"},
	COUNTRY_ISO3_PAK	: { en:"Pakistan"},
	COUNTRY_ISO3_PAN	: { en:"Panama"},
	COUNTRY_ISO3_PCN	: { en:"Pitcairn Island"},
	COUNTRY_ISO3_PER	: { en:"Peru"},
	COUNTRY_ISO3_PHL	: { en:"Philippines"},
	COUNTRY_ISO3_PLW	: { en:"Palau"},
	COUNTRY_ISO3_PNG	: { en:"Papua New Guinea"},
	COUNTRY_ISO3_POL	: { en:"Poland"},
	COUNTRY_ISO3_PRT	: { en:"Portugal"},
	COUNTRY_ISO3_PRY	: { en:"Paraguay"},
	COUNTRY_ISO3_PYF	: { en:"French Polynesia"},
	COUNTRY_ISO3_QAT	: { en:"Qatar"},
	COUNTRY_ISO3_ROU	: { en:"Romania"},
	COUNTRY_ISO3_RUS	: { en:"Russian Federation"},
	COUNTRY_ISO3_RWA	: { en:"Rwanda"},
	COUNTRY_ISO3_SAU	: { en:"Saudi Arabia"},
	COUNTRY_ISO3_SDN	: { en:"Sudan"},
	COUNTRY_ISO3_SEN	: { en:"Senegal"},
	COUNTRY_ISO3_SGP	: { en:"Singapore"},
	COUNTRY_ISO3_SLB	: { en:"Solomon Islands"},
	COUNTRY_ISO3_SLE	: { en:"Sierra Leone"},
	COUNTRY_ISO3_SLV	: { en:"El Salvador"},
	COUNTRY_ISO3_SMR	: { en:"San Marino"},
	COUNTRY_ISO3_SOM	: { en:"Somalia"},
	COUNTRY_ISO3_SPM	: { en:"France (in relation to Saint Pierre and Miquelon)"},
	COUNTRY_ISO3_STP	: { en:"Sao Tome And Principe"},
	COUNTRY_ISO3_SLE	: { en:"Sierra Leone"},
	COUNTRY_ISO3_SUR	: { en:"Suriname"},
	COUNTRY_ISO3_SWE	: { en:"Sweden"},
	COUNTRY_ISO3_SWZ	: { en:"Swaziland"},
	COUNTRY_ISO3_SVK	: { en:"Slovakia"},
	COUNTRY_ISO3_SVN	: { en:"Slovenia"},
	COUNTRY_ISO3_SLB	: { en:"Solomon Islands"},
	COUNTRY_ISO3_CHE	: { en:"Switzerland"},
	COUNTRY_ISO3_SYC	: { en:"Seychelles"},
	COUNTRY_ISO3_SYR	: { en:"Syrian Arab Republic"},
	COUNTRY_ISO3_TCA	: { en:"Turks and Caicos Islands"},
	COUNTRY_ISO3_TCD	: { en:"Chad"},
	COUNTRY_ISO3_TGO	: { en:"Togo"},
	COUNTRY_ISO3_THA	: { en:"Thailand"},
	COUNTRY_ISO3_TJK	: { en:"Kyrgyzstan"},
	COUNTRY_ISO3_TKL	: { en:"Tokelau"},
	COUNTRY_ISO3_TON	: { en:"Tonga"},
	COUNTRY_ISO3_TTO	: { en:"Trinidad and Tobago"},
	COUNTRY_ISO3_TUV	: { en:"Tuvalu"},
	COUNTRY_ISO3_TUN	: { en:"Tunisia"},
	COUNTRY_ISO3_TUR	: { en:"Turkey"},
	COUNTRY_ISO3_TWN	: { en:"Taiwan Province of China"},
	COUNTRY_ISO3_UKX	: { en:"United Kingdom (in relation to Other Territories)"},
	COUNTRY_ISO3_TZA	: { en:"United Rep of Tanzania"},
	COUNTRY_ISO3_UGA	: { en:"Uganda"},
	COUNTRY_ISO3_UKR	: { en:"Ukraine"},
	COUNTRY_ISO3_URY	: { en:"Uruguay"},
	COUNTRY_ISO3_USA	: { en:"United States of America"},
	COUNTRY_ISO3_VCT	: { en:"Saint Vincent and the Grenadines"},
	COUNTRY_ISO3_VGB	: { en:"British Virgin Islands (UK)"},
	COUNTRY_ISO3_VEN	: { en:"Venezuela"},
	COUNTRY_ISO3_VNM	: { en:"Viet Nam"},
	COUNTRY_ISO3_VUT	: { en:"Vanuatu"},
	COUNTRY_ISO3_WLF	: { en:"Wallis and Futuna"},
	COUNTRY_ISO3_WSM	: { en:"Samoa"},
	COUNTRY_ISO3_YEM	: { en:"Yemen"},
	COUNTRY_ISO3_ZAF	: { en:"South Africa"},
	COUNTRY_ISO3_ZMB	: { en:"Zambia"},
	COUNTRY_ISO3_ZWE	: { en:"Zimbabwe"},
	//SIDE PANEL
	SIDP_MAP			: {en:"Map"},
	SIDP_LAYERS			: {en:"Layers"},
	SIDP_LEGEND			: {en:"Legend"},
	SIDP_SEARCH			: {en:"Search"},
	SIDP_CLEAR			: {en:"Clear"},
	SIDP_NOGEOMETRY     : {en:"Area isn't defined yet!"},    
	SIDP_NOFEATURES     : {en:"The server did not return any feature !"},
    //ZOOMTO RFB LABELS
    ZOOMTO_RFB_LBL		: {en:"RFB ZoomTo"},
    //ZOOMTO RFB EMPTY
    ZOOMTO_RFB_EMP		: {en:"Select RFB..."},
    // SEARCH NO RESULT LABEL
    ZOOMTO_NO_RES		: {en:'RFB not found'},
    ZOOMTO_LOADING		: {en:'Loading'},
	//SEARCH FIELDS LABELS
	SEARCH_TEXT_LBL		: {en:"Free text search"},
	SEARCH_RFMO_LBL		: {en:"By Management Body/Authority(ies)"},
	SEARCH_TYPE_LBL		: {en:"By Area Type"},
	SEARCH_STAT_LBL		: {en:"By Status"},
	SEARCH_CRIT_LBL		: {en:"By VME Criteria"},
	SEARCH_YEAR_LBL		: {en:"By Year"},
	//SEARCH EMPTY TEXT
	SEARCH_TEXT_EMP		: {en:"Free text"},
	SEARCH_RFMO_EMP		: {en:"Select..."},
	SEARCH_TYPE_EMP		: {en:"Select..."},
	SEARCH_STAT_EMP		: {en:"Select..."},
	SEARCH_CRIT_EMP		: {en:"Select..."},
	SEARCH_YEAR_EMP		: {en:"Select..."},
	// SEARCH NO RESULT LABEL
	SEARCH_NO_RES		: {en:'Nothing to display'},
	SEARCH_LOADING		: {en:'Loading'},
	SEARCH_BACK_FORM	: {en:'&laquo; Back to search'},
	//VME AREA TYPES
	VME_TYPE_VME		: { en:"VME"},
	VME_TYPE_RISK		: { en:"Risk Area"},
	VME_TYPE_BPA		: { en:"Benthic protected area"},
	VME_TYPE_CLOSED		: { en:"Closed area"},
	VME_TYPE_OTHER		: { en:"Other types of managed areas"},
	//VME STATUSES 
	VME_STATUS_RSK		: { en:"Risk"},
	VME_STATUS_ENS		: { en:"Established"},
	VME_STATUS_UNDEST	: { en:"Under establishment"},
	VME_STATUS_VOL		: { en:"Voluntary"},
	VME_STATUS_EXP		: { en:"Exploratory"},
	VME_STATUS_POT		: { en:"Potential"},
	VME_STATUS_TEMP		: { en:"Temporary"},
	//VME CRITERIA 
	VME_CRITERIA_UNIQUE	: { en:"Uniqueness or rarity"},
	VME_CRITERIA_FUNCT	: { en:"Functional significance of the habitat"},
	VME_CRITERIA_FRAG	: { en:"Fragility"},
	VME_CRITERIA_LIFE	: { en:"Life-history traits"},
	VME_CRITERIA_STRUCT	: { en:"Structural complexity"},
	VME_CRITERIA_NOTS	: { en:"Not specified"},
	
	//SUB_TITLE           : { en:"The Vulnerable Marine Ecosystems Database (VME-DB)<br />gathers information on VME areas stored in harmonized<br />way and disseminated through maps and fact sheets."},
	SUB_TITLE           : { en:"Global inventory of fisheries measures adopted in ABNJ <br />to prevent significant adverse impacts of high-seas <br />bottom fisheries on vulnerable marine ecosystems (VMEs) and associated information"},
	
	LEGEND_NOTE_SIOFA	: "The Agreement is subject to ratification, acceptance or approval by the signatories.<br />The signatories and the participants that have deposited their instruments can be found <a href=\"http://www.fao.org/Legal/treaties/035s-e.htm\" target=\"_blank\">here</a>.",
	LEGEND_NOTE_SPRFMO	: "The Convention is subject to ratification, acceptance or approval by the signatories<br />The signatories and the participants that have deposited their instruments can be found <a href=\"http://www.southpacificrfmo.org/status-of-the-convention\" target=\"_blank\">here</a>.",
	LEGEND_NOTE_CACFAC	: "<br><i>In December 2009 the following countries were officially invited by the Director General to become member of the Commission: Armenia, Azerbaijan, People's Republic China, Georgia, Islamic Republic of Iran, Kazakhstan, Kyrgyzstan, Russian Federation, Tajikistan, Turkey, Turkmenistan, Uzbekistan, Afghanistan, Mongolia and Ukraine.</i>",
	SELECT_AN_RFB		: '(Select a competent authority)',
    SELECT_AN_AREA      : '(Select an area)',
	DISCLAIMER			: "<strong>Disclaimer:</strong> The designations employed and the presentation of material in the map(s) are for illustration only and do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or constitutional status of any country, territory or sea area, or concerning the delimitation of frontiers or boundaries.",
	defined			: true
};
